POST http://localhost:8181/utilisateur/add
Content-Type: application/json

{
	"login": "login",
        "password":"password",
        "mail": "mail",
        "idprofil": 1,
        "tel":"mail",
        "nom":"mail",
        "prenom":"mail"
}

