POST http://localhost:8181/client/add
Content-Type: application/json

{
        "mail": "mail",
        "ville": 2,
        "tel":"mail",
        "nom":"mail",
        "code":"mail",
				"addresse": "wefjk"
}

