const BASE_URL = process.env.REACT_APP_PROD_API
const UPLOAD_SERVICE_API = process.env.REACT_APP_UPLOAD_SERVICE_API
const EMAIL_API = process.env.REACT_APP_EMAIL_API
const ENVIRONMENT = process.env.REACT_APP_ENVIRONMENT
const RECAPTCHA_PUBLIC_KEY = process.env.REACT_APP_RECAPTCHA_PUBLIC_KEY
const APP_URL = process.env.REACT_APP_URL
const APP_NAME = process.env.REACT_APP_NAME
const LANDING_PAGE_URL = process.env.REACT_APP_LANDING_PAGE_URL
const GA_ANALYTICS_KEY = process.env.REACT_APP_GA_ANALYTICS_KEY
const TWITTER_ACCOUNT_URL = process.env.REACT_APP_TWITTER_ACCOUNT_URL
const SENTRY_KEY = process.env.REACT_APP_SENTRY_KEY

export {
  BASE_URL,
  UPLOAD_SERVICE_API,
  EMAIL_API,
  ENVIRONMENT,
  RECAPTCHA_PUBLIC_KEY,
  APP_URL,
  APP_NAME,
  LANDING_PAGE_URL,
  GA_ANALYTICS_KEY,
  TWITTER_ACCOUNT_URL,
  SENTRY_KEY,
}
