module.exports = {
  BASE_URL: process.env.REACT_APP_PROD_API,
  UPLOAD_SERVICE_API: process.env.REACT_APP_UPLOAD_SERVICE_API,
  EMAIL_API: process.env.REACT_APP_EMAIL_API,
  ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
}
