module.exports = {
  BASE_URL: process.env.REACT_APP_PROD_API,
  UPLOAD_SERVICE_API: process.env.REACT_APP_UPLOAD_SERVICE_API,
  EMAIL_API: process.env.REACT_APP_EMAIL_API,
  ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
  RECAPTCHA_PUBLIC_KEY: process.env.REACT_APP_RECAPTCHA_PUBLIC_KEY,
  APP_URL: process.env.REACT_APP_URL,
  APP_NAME: process.env.REACT_APP_NAME,
  LANDING_PAGE_URL: process.env.REACT_APP_LANDING_PAGE_URL,
  GA_ANALYTICS_KEY: process.env.REACT_APP_GA_ANALYTICS_KEY,
  TWITTER_ACCOUNT_URL: process.env.REACT_APP_TWITTER_ACCOUNT_URL,
  SENTRY_KEY: process.env.REACT_APP_SENTRY_KEY,
}
